import Homes from '@/components/Home/Homes'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Polaris</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Homes/>
      
    </>
  )
}
